Repository profcomff/design-school-api, pull requests merged in 2022-11, with the labels that each got.

#2 Backend init
  .github/workflows/build_and_publish.yml
  .gitignore
  Dockerfile
  Makefile
  design_bot/__main__.py
  design_bot/exceptions.py
  design_bot/methods/__init__.py
  design_bot/methods/google_drive.py
  design_bot/models/__init__.py
  design_bot/models/db.py
  design_bot/routes/base.py
  design_bot/routes/directions.py
  design_bot/routes/models/models.py
  design_bot/routes/registration.py
  design_bot/routes/response.py
  design_bot/routes/uservideo.py
  design_bot/routes/videos.py
  design_bot/settings.py
  migrations/versions/6feaabe4cc2d_init.py
  requirements.txt
  static/.gitkeep
Labels: new feature

#3 Docker fix
  Dockerfile
Labels: bug

#4 fix build
  .github/workflows/build_and_publish.yml
Labels: bug

#5 fix deploy
  .github/workflows/build_and_publish.yml
Labels: bug

#6 fix req's
  requirements.txt
Labels: bug

#8 Ref
  .github/workflows/build_and_publish.yml
  design_bot/exceptions.py
  design_bot/methods/auth.py
  design_bot/methods/google_drive.py
  design_bot/models/__init__.py
  design_bot/models/base.py
  design_bot/models/db.py
  design_bot/routes/auth.py
  design_bot/routes/base.py
  design_bot/routes/directions.py
  design_bot/routes/models/base.py
  design_bot/routes/models/models.py
  design_bot/routes/registration.py
  design_bot/routes/response.py
  design_bot/routes/spam.py
  design_bot/routes/uservideo.py
  design_bot/routes/videos.py
  design_bot/settings.py
  migrations/versions/6feaabe4cc2d_init.py
  migrations/versions/d124a172c3b3_unique_id.py
Labels: wontfix

#9 URL fix
  .github/workflows/build_and_publish.yml
Labels: bug

#10 Spam router fix
  design_bot/routes/base.py
  design_bot/routes/spam.py
Labels: bug

#11 readme user add to gdrive
  design_bot/routes/registration.py
Labels: new feature

#13 Get users list added
  design_bot/routes/registration.py
Labels: new feature

#14 404 fix
  design_bot/routes/registration.py
Labels: bug

#17 pool_pre_ping add
  design_bot/routes/base.py
  design_bot/settings.py
Labels: new feature
